### ISSUE TITLE
HMA Request

### ISSUE THREAD

**Issue by BradT7** [Gab0/gekko-extra-indicators#2]
Hi @Gab0 Would you be able to code this indicator for us! I would like to replace SMA with HMA in some strategies. I've found the math, but not quite sure how to code it effectively. 

Here's what I found! 
[HMA](https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/hull-moving-average)
HMA= WMA(2*WMA(n/2) − WMA(n)),sqrt(n))

Which also requires [WMA](https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/wma)
WMA = (P1 * 5) + (P2 * 4) + (P3 * 3) + (P4 * 2) + (P5 * 1) / (5 + 4+ 3 + 2 + 1)
Where:
P1 = current price
P2 = price one bar ago, etc…

**Comment by Gab0** [comment]
cool.
