### ISSUE TITLE
Failed to load indicator STC

### ISSUE THREAD

**Issue by hi-too** [Gab0/gekko-extra-indicators#3]
Hello dear developer,

First of all.. thanks a lot for providing these indicators..

I've an issue, when I run a backtest, I see this message:

`2018-06-05 04:30:31 (ERROR):    Failed to load indicator STC`

I'm using latest version of Gekko, and latest version of your indicators.

Could you please help?!

**Comment by Gab0** [comment]
Hey, to use STC you need the indicator STOCH, which I forgot to add here XD
Added.

**Comment by hi-too** [comment]
Thanks a lot..

You Rock!
